apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-aws-monitor.fullname" . }}-aws-credentials
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  access_key: {{ .Values.aws.credentials.access_key }}
  secret_key: {{ .Values.aws.credentials.secret_key }} 