apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-monitor
  labels:
    app: aws-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-monitor
  template:
    metadata:
      labels:
        app: aws-monitor
    spec:
      containers:
      - name: aws-monitor
        image: amit142/aws-monitor:latest
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: PORT
          value: "5001"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          value: "us-east-1" 