apiVersion: v1
kind: Service
metadata:
  name: aws-monitor-service
  labels:
    app: aws-monitor
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  selector:
    app: aws-monitor 